/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

<<<<<<< HEAD
import { createFileRoute } from '@tanstack/react-router'
=======
import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DosenDashboardRouteImport } from './routes/dosen/dashboard'
import { Route as DosenAssignmentRouteImport } from './routes/dosen/assignment'
import { Route as DosenAddAssignmentRouteImport } from './routes/dosen/add-assignment'
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as UploadRouteImport } from './routes/upload.tsx'
import { Route as RoleSelectionRouteImport } from './routes/role-selection.tsx'
import { Route as MahasiswaRouteImport } from './routes/mahasiswa.tsx'
import { Route as IndexRouteImport } from './routes/index.tsx'
import { Route as DosenIndexRouteImport } from './routes/dosen/index.tsx'
import { Route as MahasiswaIndexRouteImport } from './routes/Mahasiswa/index.tsx'
import { Route as DosenGradingRouteImport } from './routes/dosen/grading.tsx'
import { Route as DosenDashboardRouteImport } from './routes/dosen/dashboard.tsx'
import { Route as DosenAssignmentRouteImport } from './routes/dosen/assignment.tsx'
import { Route as DosenAddAssignmentRouteImport } from './routes/dosen/add-assignment.tsx'
import { Route as MahasiswaRegisterRouteImport } from './routes/Mahasiswa/register.tsx'
import { Route as MahasiswaLoginRouteImport } from './routes/Mahasiswa/login.tsx'
import { Route as MahasiswaDashboardRouteImport } from './routes/Mahasiswa/dashboard.tsx'

const MahasiswaTugasLazyRouteImport = createFileRoute('/Mahasiswa/tugas')()
const MahasiswaNilaiLazyRouteImport = createFileRoute('/Mahasiswa/nilai')()

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleSelectionRoute = RoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const MahasiswaRoute = MahasiswaRouteImport.update({
  id: '/mahasiswa',
  path: '/mahasiswa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const DosenIndexRoute = DosenIndexRouteImport.update({
  id: '/dosen/',
  path: '/dosen/',
  getParentRoute: () => rootRouteImport,
} as any)
const MahasiswaIndexRoute = MahasiswaIndexRouteImport.update({
  id: '/Mahasiswa/',
  path: '/Mahasiswa/',
  getParentRoute: () => rootRouteImport,
} as any)
const MahasiswaTugasLazyRoute = MahasiswaTugasLazyRouteImport.update({
  id: '/Mahasiswa/tugas',
  path: '/Mahasiswa/tugas',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/Mahasiswa/tugas.lazy.tsx').then((d) => d.Route),
)
const MahasiswaNilaiLazyRoute = MahasiswaNilaiLazyRouteImport.update({
  id: '/Mahasiswa/nilai',
  path: '/Mahasiswa/nilai',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/Mahasiswa/nilai.lazy.tsx').then((d) => d.Route),
)
const DosenGradingRoute = DosenGradingRouteImport.update({
  id: '/dosen/grading',
  path: '/dosen/grading',
  getParentRoute: () => rootRouteImport,
} as any)
=======
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
const DosenDashboardRoute = DosenDashboardRouteImport.update({
  id: '/dosen/dashboard',
  path: '/dosen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenAssignmentRoute = DosenAssignmentRouteImport.update({
  id: '/dosen/assignment',
  path: '/dosen/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenAddAssignmentRoute = DosenAddAssignmentRouteImport.update({
  id: '/dosen/add-assignment',
  path: '/dosen/add-assignment',
  getParentRoute: () => rootRouteImport,
} as any)
<<<<<<< HEAD
const MahasiswaRegisterRoute = MahasiswaRegisterRouteImport.update({
  id: '/Mahasiswa/register',
  path: '/Mahasiswa/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MahasiswaLoginRoute = MahasiswaLoginRouteImport.update({
  id: '/Mahasiswa/login',
  path: '/Mahasiswa/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MahasiswaDashboardRoute = MahasiswaDashboardRouteImport.update({
  id: '/Mahasiswa/dashboard',
  path: '/Mahasiswa/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mahasiswa': typeof MahasiswaRoute
  '/role-selection': typeof RoleSelectionRoute
  '/upload': typeof UploadRoute
  '/Mahasiswa/dashboard': typeof MahasiswaDashboardRoute
  '/Mahasiswa/login': typeof MahasiswaLoginRoute
  '/Mahasiswa/register': typeof MahasiswaRegisterRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
  '/dosen/grading': typeof DosenGradingRoute
  '/Mahasiswa/nilai': typeof MahasiswaNilaiLazyRoute
  '/Mahasiswa/tugas': typeof MahasiswaTugasLazyRoute
  '/Mahasiswa': typeof MahasiswaIndexRoute
  '/dosen': typeof DosenIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mahasiswa': typeof MahasiswaRoute
  '/role-selection': typeof RoleSelectionRoute
  '/upload': typeof UploadRoute
  '/Mahasiswa/dashboard': typeof MahasiswaDashboardRoute
  '/Mahasiswa/login': typeof MahasiswaLoginRoute
  '/Mahasiswa/register': typeof MahasiswaRegisterRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
  '/dosen/grading': typeof DosenGradingRoute
  '/Mahasiswa/nilai': typeof MahasiswaNilaiLazyRoute
  '/Mahasiswa/tugas': typeof MahasiswaTugasLazyRoute
  '/Mahasiswa': typeof MahasiswaIndexRoute
  '/dosen': typeof DosenIndexRoute
=======

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/mahasiswa': typeof MahasiswaRoute
  '/role-selection': typeof RoleSelectionRoute
  '/upload': typeof UploadRoute
  '/Mahasiswa/dashboard': typeof MahasiswaDashboardRoute
  '/Mahasiswa/login': typeof MahasiswaLoginRoute
  '/Mahasiswa/register': typeof MahasiswaRegisterRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
  '/dosen/grading': typeof DosenGradingRoute
  '/Mahasiswa/nilai': typeof MahasiswaNilaiLazyRoute
  '/Mahasiswa/tugas': typeof MahasiswaTugasLazyRoute
  '/Mahasiswa/': typeof MahasiswaIndexRoute
  '/dosen/': typeof DosenIndexRoute
=======
  '/login': typeof LoginRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
<<<<<<< HEAD
    | '/mahasiswa'
    | '/role-selection'
    | '/upload'
    | '/Mahasiswa/dashboard'
    | '/Mahasiswa/login'
    | '/Mahasiswa/register'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
    | '/dosen/grading'
    | '/Mahasiswa/nilai'
    | '/Mahasiswa/tugas'
    | '/Mahasiswa'
    | '/dosen'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mahasiswa'
    | '/role-selection'
    | '/upload'
    | '/Mahasiswa/dashboard'
    | '/Mahasiswa/login'
    | '/Mahasiswa/register'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
    | '/dosen/grading'
    | '/Mahasiswa/nilai'
    | '/Mahasiswa/tugas'
    | '/Mahasiswa'
    | '/dosen'
  id:
    | '__root__'
    | '/'
    | '/mahasiswa'
    | '/role-selection'
    | '/upload'
    | '/Mahasiswa/dashboard'
    | '/Mahasiswa/login'
    | '/Mahasiswa/register'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
    | '/dosen/grading'
    | '/Mahasiswa/nilai'
    | '/Mahasiswa/tugas'
    | '/Mahasiswa/'
    | '/dosen/'
=======
    | '/login'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  MahasiswaRoute: typeof MahasiswaRoute
  RoleSelectionRoute: typeof RoleSelectionRoute
  UploadRoute: typeof UploadRoute
  MahasiswaDashboardRoute: typeof MahasiswaDashboardRoute
  MahasiswaLoginRoute: typeof MahasiswaLoginRoute
  MahasiswaRegisterRoute: typeof MahasiswaRegisterRoute
  DosenAddAssignmentRoute: typeof DosenAddAssignmentRoute
  DosenAssignmentRoute: typeof DosenAssignmentRoute
  DosenDashboardRoute: typeof DosenDashboardRoute
  DosenGradingRoute: typeof DosenGradingRoute
  MahasiswaNilaiLazyRoute: typeof MahasiswaNilaiLazyRoute
  MahasiswaTugasLazyRoute: typeof MahasiswaTugasLazyRoute
  MahasiswaIndexRoute: typeof MahasiswaIndexRoute
  DosenIndexRoute: typeof DosenIndexRoute
=======
  LoginRoute: typeof LoginRoute
  DosenAddAssignmentRoute: typeof DosenAddAssignmentRoute
  DosenAssignmentRoute: typeof DosenAssignmentRoute
  DosenDashboardRoute: typeof DosenDashboardRoute
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-selection': {
      id: '/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof RoleSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mahasiswa': {
      id: '/mahasiswa'
      path: '/mahasiswa'
      fullPath: '/mahasiswa'
      preLoaderRoute: typeof MahasiswaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/dosen/': {
      id: '/dosen/'
      path: '/dosen'
      fullPath: '/dosen'
      preLoaderRoute: typeof DosenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mahasiswa/': {
      id: '/Mahasiswa/'
      path: '/Mahasiswa'
      fullPath: '/Mahasiswa'
      preLoaderRoute: typeof MahasiswaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mahasiswa/tugas': {
      id: '/Mahasiswa/tugas'
      path: '/Mahasiswa/tugas'
      fullPath: '/Mahasiswa/tugas'
      preLoaderRoute: typeof MahasiswaTugasLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mahasiswa/nilai': {
      id: '/Mahasiswa/nilai'
      path: '/Mahasiswa/nilai'
      fullPath: '/Mahasiswa/nilai'
      preLoaderRoute: typeof MahasiswaNilaiLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/grading': {
      id: '/dosen/grading'
      path: '/dosen/grading'
      fullPath: '/dosen/grading'
      preLoaderRoute: typeof DosenGradingRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
    '/dosen/dashboard': {
      id: '/dosen/dashboard'
      path: '/dosen/dashboard'
      fullPath: '/dosen/dashboard'
      preLoaderRoute: typeof DosenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/assignment': {
      id: '/dosen/assignment'
      path: '/dosen/assignment'
      fullPath: '/dosen/assignment'
      preLoaderRoute: typeof DosenAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/add-assignment': {
      id: '/dosen/add-assignment'
      path: '/dosen/add-assignment'
      fullPath: '/dosen/add-assignment'
      preLoaderRoute: typeof DosenAddAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
<<<<<<< HEAD
    '/Mahasiswa/register': {
      id: '/Mahasiswa/register'
      path: '/Mahasiswa/register'
      fullPath: '/Mahasiswa/register'
      preLoaderRoute: typeof MahasiswaRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mahasiswa/login': {
      id: '/Mahasiswa/login'
      path: '/Mahasiswa/login'
      fullPath: '/Mahasiswa/login'
      preLoaderRoute: typeof MahasiswaLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Mahasiswa/dashboard': {
      id: '/Mahasiswa/dashboard'
      path: '/Mahasiswa/dashboard'
      fullPath: '/Mahasiswa/dashboard'
      preLoaderRoute: typeof MahasiswaDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
=======
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  MahasiswaRoute: MahasiswaRoute,
  RoleSelectionRoute: RoleSelectionRoute,
  UploadRoute: UploadRoute,
  MahasiswaDashboardRoute: MahasiswaDashboardRoute,
  MahasiswaLoginRoute: MahasiswaLoginRoute,
  MahasiswaRegisterRoute: MahasiswaRegisterRoute,
  DosenAddAssignmentRoute: DosenAddAssignmentRoute,
  DosenAssignmentRoute: DosenAssignmentRoute,
  DosenDashboardRoute: DosenDashboardRoute,
  DosenGradingRoute: DosenGradingRoute,
  MahasiswaNilaiLazyRoute: MahasiswaNilaiLazyRoute,
  MahasiswaTugasLazyRoute: MahasiswaTugasLazyRoute,
  MahasiswaIndexRoute: MahasiswaIndexRoute,
  DosenIndexRoute: DosenIndexRoute,
=======
  LoginRoute: LoginRoute,
  DosenAddAssignmentRoute: DosenAddAssignmentRoute,
  DosenAssignmentRoute: DosenAssignmentRoute,
  DosenDashboardRoute: DosenDashboardRoute,
>>>>>>> 52e54420f9f508166adbb22a83d0f677f6a8e064
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
