/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DosenGradingRouteImport } from './routes/dosen/grading'
import { Route as DosenDashboardRouteImport } from './routes/dosen/dashboard'
import { Route as DosenAssignmentRouteImport } from './routes/dosen/assignment'
import { Route as DosenAddAssignmentRouteImport } from './routes/dosen/add-assignment'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenGradingRoute = DosenGradingRouteImport.update({
  id: '/dosen/grading',
  path: '/dosen/grading',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenDashboardRoute = DosenDashboardRouteImport.update({
  id: '/dosen/dashboard',
  path: '/dosen/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenAssignmentRoute = DosenAssignmentRouteImport.update({
  id: '/dosen/assignment',
  path: '/dosen/assignment',
  getParentRoute: () => rootRouteImport,
} as any)
const DosenAddAssignmentRoute = DosenAddAssignmentRouteImport.update({
  id: '/dosen/add-assignment',
  path: '/dosen/add-assignment',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
  '/dosen/grading': typeof DosenGradingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
  '/dosen/grading': typeof DosenGradingRoute
=======
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
>>>>>>> example
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
<<<<<<< HEAD
  '/dosen/add-assignment': typeof DosenAddAssignmentRoute
  '/dosen/assignment': typeof DosenAssignmentRoute
  '/dosen/dashboard': typeof DosenDashboardRoute
  '/dosen/grading': typeof DosenGradingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
    | '/dosen/grading'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
    | '/dosen/grading'
  id:
    | '__root__'
    | '/'
    | '/dosen/add-assignment'
    | '/dosen/assignment'
    | '/dosen/dashboard'
    | '/dosen/grading'
=======
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login'
  id: '__root__' | '/' | '/login'
>>>>>>> example
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
<<<<<<< HEAD
  DosenAddAssignmentRoute: typeof DosenAddAssignmentRoute
  DosenAssignmentRoute: typeof DosenAssignmentRoute
  DosenDashboardRoute: typeof DosenDashboardRoute
  DosenGradingRoute: typeof DosenGradingRoute
=======
  LoginRoute: typeof LoginRoute
>>>>>>> example
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/grading': {
      id: '/dosen/grading'
      path: '/dosen/grading'
      fullPath: '/dosen/grading'
      preLoaderRoute: typeof DosenGradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/dashboard': {
      id: '/dosen/dashboard'
      path: '/dosen/dashboard'
      fullPath: '/dosen/dashboard'
      preLoaderRoute: typeof DosenDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/assignment': {
      id: '/dosen/assignment'
      path: '/dosen/assignment'
      fullPath: '/dosen/assignment'
      preLoaderRoute: typeof DosenAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dosen/add-assignment': {
      id: '/dosen/add-assignment'
      path: '/dosen/add-assignment'
      fullPath: '/dosen/add-assignment'
      preLoaderRoute: typeof DosenAddAssignmentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
<<<<<<< HEAD
  DosenAddAssignmentRoute: DosenAddAssignmentRoute,
  DosenAssignmentRoute: DosenAssignmentRoute,
  DosenDashboardRoute: DosenDashboardRoute,
  DosenGradingRoute: DosenGradingRoute,
=======
  LoginRoute: LoginRoute,
>>>>>>> example
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
