// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, formDataBodySerializer } from './client';
import type { GetData, GetResponses, PostRegisterData, PostRegisterResponses, PostRegisterErrors, PostLoginData, PostLoginResponses, PostLoginErrors, GetRefreshTokenData, GetRefreshTokenResponses, GetRefreshTokenErrors, GetUserProfileData, GetUserProfileResponses, GetUserProfileErrors, PostCreateAssignmentData, PostCreateAssignmentResponses, PostCreateAssignmentErrors, GetAssignmentData, GetAssignmentResponses, GetAssignmentErrors, GetSubmissionData, GetSubmissionResponses, PostSubmissionData, PostSubmissionResponses, PostSubmissionErrors } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const get = <ThrowOnError extends boolean = false>(options?: Options<GetData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetResponses, unknown, ThrowOnError>({
        url: '/',
        ...options
    });
};

export const postRegister = <ThrowOnError extends boolean = false>(options: Options<PostRegisterData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostRegisterResponses, PostRegisterErrors, ThrowOnError>({
        url: '/register',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const postLogin = <ThrowOnError extends boolean = false>(options: Options<PostLoginData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostLoginResponses, PostLoginErrors, ThrowOnError>({
        url: '/login',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getRefreshToken = <ThrowOnError extends boolean = false>(options?: Options<GetRefreshTokenData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetRefreshTokenResponses, GetRefreshTokenErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/refresh-token',
        ...options
    });
};

export const getUserProfile = <ThrowOnError extends boolean = false>(options?: Options<GetUserProfileData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetUserProfileResponses, GetUserProfileErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/user-profile',
        ...options
    });
};

export const postCreateAssignment = <ThrowOnError extends boolean = false>(options: Options<PostCreateAssignmentData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostCreateAssignmentResponses, PostCreateAssignmentErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/create/assignment',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

export const getAssignment = <ThrowOnError extends boolean = false>(options?: Options<GetAssignmentData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetAssignmentResponses, GetAssignmentErrors, ThrowOnError>({
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/assignment',
        ...options
    });
};

export const getSubmission = <ThrowOnError extends boolean = false>(options?: Options<GetSubmissionData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetSubmissionResponses, unknown, ThrowOnError>({
        url: '/submission',
        ...options
    });
};

export const postSubmission = <ThrowOnError extends boolean = false>(options: Options<PostSubmissionData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<PostSubmissionResponses, PostSubmissionErrors, ThrowOnError>({
        ...formDataBodySerializer,
        security: [
            {
                scheme: 'bearer',
                type: 'http'
            }
        ],
        url: '/submission',
        ...options,
        headers: {
            'Content-Type': null,
            ...options.headers
        }
    });
};