// This file is auto-generated by @hey-api/openapi-ts

export type GetAllUser = {
    data?: Array<{
        id?: number;
        createdAt?: string;
        updatedAt?: string;
        name?: string;
        email?: string;
        username?: string;
        password?: string;
    }>;
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type GetUsersErrors = {
    /**
     * Internal Server Error
     */
    500: GetAllUser;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * OK
     */
    200: GetAllUser;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3000' | (string & {});
};