// This file is auto-generated by @hey-api/openapi-ts

export type LoginRequest = {
    email?: string;
    password?: string;
};

export type RegisterRequest = {
    name?: string;
    nim?: string;
    email?: string;
    password?: string;
};

export type LoginResponse = {
    message?: string;
    tokens?: {
        accessToken?: string;
        refreshToken?: string;
    };
};

export type RegisterResponse = {
    message?: string;
    data?: {
        id?: number;
        createdAt?: string;
        updatedAt?: string;
        deletedAt?: unknown;
        name?: string;
        email?: string;
        role?: string;
    };
};

export type RefreshAccessTokenResponse = {
    message?: string;
    tokens?: {
        accessToken?: string;
    };
};

export type UserProfileResponse = {
    message?: string;
    data?: {
        user?: {
            id?: number;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: unknown;
            name?: string;
            email?: string;
            role?: string;
        };
    };
};

export type GetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type GetResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostRegisterData = {
    body: RegisterRequest;
    path?: never;
    query?: never;
    url: '/register';
};

export type PostRegisterErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostRegisterResponses = {
    /**
     * OK
     */
    200: RegisterResponse;
    /**
     * Created
     */
    201: unknown;
};

export type PostRegisterResponse = PostRegisterResponses[keyof PostRegisterResponses];

export type PostLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/login';
};

export type PostLoginErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type PostLoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type PostLoginResponse = PostLoginResponses[keyof PostLoginResponses];

export type GetRefreshTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/refresh-token';
};

export type GetRefreshTokenErrors = {
    /**
     * Bad Request
     */
    400: unknown;
};

export type GetRefreshTokenResponses = {
    /**
     * OK
     */
    200: RefreshAccessTokenResponse;
};

export type GetRefreshTokenResponse = GetRefreshTokenResponses[keyof GetRefreshTokenResponses];

export type GetUserProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user-profile';
};

export type GetUserProfileErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * Internal Server Error
     */
    500: unknown;
};

export type GetUserProfileResponses = {
    /**
     * User profile retrieved successfully.
     */
    200: UserProfileResponse;
};

export type GetUserProfileResponse = GetUserProfileResponses[keyof GetUserProfileResponses];

export type ClientOptions = {
    baseUrl: 'http://localhost:3001/api/v1' | (string & {});
};